import Logo from "@public/devin.png";
import LogoDarkMode from "@public/devin2.png";
import { useAppStore } from "@states/app";
import { cx } from "@utils/tools";
import Head from "next/head";
import Image from "next/image";

export const MainLayout: IComponent = ({ children }) => {
  // Manual switch darkMode with state
  const { darkMode } = useAppStore();
  console.log(darkMode);

  return (
    <div
      className={cx(
        {
          dark: darkMode === "dark",
        },
        "w-full min-h-screen font-serif"
      )}
    >
      <div className="w-full transition-all dark:bg-black dark:text-white bg-white text-black">
        <Head>
          <title>NEXTJS TEMPLATE</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="w-full bg-cover bg-center">{children}</div>
        <footer className="sticky flex pb-8  justify-center items-center">
          <span className="mx-40 pt-4 border-t border-[#eaeaea] flex-grow text-center ">
            <a
              className="cursor-pointer"
              target="_blank"
              href="https://www.wearedevin.com/"
              rel="noreferrer"
            >
              Powered by{" "}
              <span className="h-4 ml-2 bg-default p-2 rounded-lg dark:bg-primary ">
                <Image
                  src={darkMode === "dark" ? LogoDarkMode : Logo}
                  alt="deVin Logo"
                  width={72}
                  height={16}
                />
              </span>
            </a>
          </span>
        </footer>
      </div>
    </div>
  );
};
